=== zhouyuansheng0618/st2web/modules/st2flow-model/schemas/metadata.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata Schema",
  "description": "A schema describing the metadata for individual workflows.",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "enabled": {
      "type": "boolean"
    },
    "uid": {
      "type": "string",
      "minLength": 1
    },
    "ref": {
      "type": "string",
      "minLength": 1
    },
    "id": {
      "type": "string",
      "minLength": 1
    },
    "entry_point": {
      "type": "string",
      "minLength": 1
    },
    "pack": {
      "type": "string",
      "minLength": 1
    },
    "runner_type": {
      "type": "string",
      "minLength": 1
    },
    "parameters": {
      "type": "object",
      "patternProperties": {
        "^\\w+$": {
          "anyOf": [
            {"type": "null"},
            {"type": "array"},
            {"type": "boolean"},
            {"type": "integer"},
            {"type": "number"},
            {"type": "object"},
            {"type": "string"}
          ]
        }
      }
    }
  }
}

=== zhouyuansheng0618/st2web/modules/st2flow-model/tests/data/meta-basic.json
{
  "runner_type": "python-script",
  "name": "format",
  "parameters": {
    "log_level": {
      "default": "DEBUG",
      "enum": [
        "AUDIT",
        "CRITICAL",
        "ERROR",
        "WARNING",
        "INFO",
        "DEBUG"
      ],
      "type": "string",
      "description": "Default log level for Python runner actions."
    },
    "env": {
      "type": "object",
      "description": "Environment variables which will be available to the script."
    },
    "quote_char": {
      "default": "\"",
      "required": false,
      "type": "string",
      "description": "Character used to quote the strings."
    },
    "delimiter": {
      "default": ",",
      "required": false,
      "type": "string",
      "description": "String delimiter character."
    },
    "timeout": {
      "default": 600,
      "type": "integer",
      "description": "Action timeout in seconds. Action will get killed if it doesn't finish in timeout seconds."
    },
    "debug": {
      "default": false,
      "required": false,
      "type": "boolean",
      "description": "Enable runner debug mode."
    },
    "content_version": {
      "required": false,
      "type": "string",
      "description": "Git revision of the pack content to use for this action execution (git commit sha / tag / branch). Only applies to packs which are git repositories."
    },
    "data": {
      "required": true,
      "type": "array",
      "description": "Data to parse"
    }
  },
  "enabled": true,
  "entry_point": "format.py",
  "uid": "action:csv:format",
  "pack": "csv",
  "ref": "csv.format",
  "id": "5bb53e261f2fa3073577789a",
  "description": "Format a Python list into a CSV string"
}
